/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  tbf_rx65n_gcc                          */
/*      FILE         :  tbf_rx65n_gcc.c                        */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "common.h"
#include "gpio.h"
#include "cmt.h"
// #include "uart.h"
// #include "groupir.h"



int main(void)
{
	uint8_t timer_status;

	gpio_create();
	cmt_create();

	led_ctrl(LED0, LED_ON);
	led_ctrl(LED1, LED_OFF);


	while(1) {
		led_toggle(LED0);
		led_toggle(LED1);
		cmtw0_start(MILLI_SEC, 500, &timer_status);
		while (!timer_status);
		led_toggle(LED0);
		led_toggle(LED1);
		cmtw1_start(MILLI_SEC, 500, &timer_status);
		while (!timer_status);
		led_toggle(LED0);
		led_toggle(LED1);
		cmtw0_start(MICRO_SEC, 50000, &timer_status);
		while (!timer_status);
		led_toggle(LED0);
		led_toggle(LED1);
		cmtw1_start(MICRO_SEC, 50000, &timer_status);
		while (!timer_status);
	}

	return 0;

}
