/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  tbf_rx65n_gcc                          */
/*      FILE         :  tbf_rx65n_gcc.c                        */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "common.h"
#include "gpio.h"
#include "cmt.h"
// #include "uart.h"
// #include "groupir.h"



int main(void)
{
	gpio_create();
	cmt_create();

	led_ctrl(LED0, LED_ON);
	led_ctrl(LED1, LED_OFF);



	while(1) {
		led_toggle(LED0);
		led_toggle(LED1);
		// cmt_wait(0, MILLI_SEC, 500);
		// led_toggle(LED0);
		// led_toggle(LED1);
		// cmt_wait(1, MILLI_SEC, 500);
		cmtw1_ir = 0;
		cmtw1_start(1, 500);
		while (cmtw1_ir != 1);

	}

	return 0;

}