/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  tbf_rx65n_gcc                          */
/*      FILE         :  tbf_rx65n_gcc.c                        */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "common.h"
#include "gpio.h"
#include "cmt.h"
// #include "uart.h"
// #include "groupir.h"



int main(void)
{
	gpio_create();
	cmt_create();


	PORTD.PODR.BIT.B6 = 0;

	while(1) {
		PORTD.PODR.BIT.B7 = 0;
		cmt_wait(0, MILLI_SEC, 500);
		PORTD.PODR.BIT.B7 = 1;
		cmt_wait(0, MILLI_SEC, 500);
	}

	return 0;

}